### ISSUE TITLE
Potential Reentrency attack with the claim function

### ISSUE THREAD

**Issue by Anas-debug** [rio-org/rio-vesting-escrow#5]
Reentrancy: The **claim** functions (**testClaimFull**, **testClaimLess**, **testClaimBeneficiary**, ...) modify the balance of the recipient after transferring funds. 
If the **token.transfer** call interacts with an external contract there's a risk of reentrancy where the external contract could call back into **claim** before the balance is updated leading to multiple withdrawals.

**Comment by solimander** [comment]
`totalClaimed` is updated prior to the token transfer, and ERC777s (ERC20s with callbacks) are not supported.
